Tab_Welcome<- 
  tabItem(tabName = "Welcome",
    fluidRow(
      box(
        title = span(icon("circle-info"), strong("Welcome to FlowMonitor")),
        background = "blue",
        width = 12,
          h4("Welcome to FlowMonitor. This R-shiny app allows visualization of QC data generated by your FlowCytometer"),
          h4("To get started, please give the app the location of your QC data by clicking choose directory in the left."),
          h4("Once you've located the data, you can continue with importing the data, by selecting the importing tab for your instrument.")
         
      ),
 
     box(
       title = span(icon("circle-info"), strong("Notes")),
       background = "aqua",
       width = 12,
        h4("Please make sure your data folders are structured correctly:"),
        h4("- Data from each instrument needs to be located in a folder named Data_XXX, with XXX representing the instrument name as will be used in the app."),
 	h4("- Data from multiple intruments from the same vendor can be processed at the same time. To achieve this, put all Data_XXX folders in one folder. Please make sure there are no other folders present in the folder"),
      
      ),

  ))