Tab_Plots_CytoflexSRT <- tabItem(tabName = "visualization_data_QC_CytoflexSRT",
  fluidRow(
    tabBox(title = "Generated graph",
          width = 10,
          height = 700,
          tabPanel("Standard Visualization", plotOutput("StandardPlotcytoflex", height = 640)),
          tabPanel("Detailed visualization", plotlyOutput("Plotlycytoflex", height = 640)),
    ),
    box(title = span(icon("chart-line"),"Press to plot"), 
        collapsible = TRUE,  
        width = 2, 
        background = "aqua", 
        side = "left",
        actionButton("Generate_Plot_cytoflex",
                     label = "Click here", 
    )),
    box(title = span(icon("image"),"Download image"), 
        collapsible = TRUE,  
        width = 2, 
        background = "teal",
        uiOutput("Image_cytoflex_plot"),
              
    ),
    box(title = span(icon("grip-lines-vertical"), "Edit axis ranges"), 
        collapsible = TRUE, 
        solidHeader = TRUE, 
        status = "primary", 
        width = 2,
        uiOutput("Ymin_cytoflex"),
        uiOutput("Ymax_cytoflex"), 
        uiOutput("Xmin_cytoflex"),
        uiOutput("Xmax_cytoflex"), 
    ),
    box(title = span(icon("filter"),"Filters"), 
        collapsible = TRUE, 
        solidHeader = TRUE, 
        width = 3, 
        status = "primary", 
        side = "left",
        uiOutput("Instruments_cytoflex"), 
        uiOutput("Parameters_cytoflex"),
        uiOutput("LasDetec_cytoflex"),
        uiOutput("PassFail_cytoflex"),        
    ), 
          
          
          
    tabBox(title = "Costumize graph & add Lines and Labels", 
           width = 6,
      tabPanel("Graph title", 
               textInput("Title_Graph_cytoflex", 
               label = "Title for graph",
               value = "Graph title")),
      tabPanel("Y-axis title", 
               textInput("Title_Yaxis_cytoflex", 
               label = "Title for y-axis",
               value = "y")),
      tabPanel("Add vertical lines", 
               checkboxGroupInput("Add_Lines_cytoflex", 
               label = "Add vertical lines",
               choices = c("Line1",
                           "Line2",
                           "Line3",
                           "Line4",
                           "Line5",
                           "Line6"))),
      tabPanel("Position", 
          dateInput("Line1_Position_cytoflex", 
                    label = "Line1",
                    value = ("2022-01-20")),
          dateInput("Line2_Position_cytoflex", 
                    label = "Line2",
                    value = ("2022-02-20")),
          dateInput("Line3_Position_cytoflex", 
                    label = "Line3",
                    value = ("2022-03-20")),
          dateInput("Line4_Position_cytoflex", 
                    label = "Line4",
                    value = ("2022-04-20")),
          dateInput("Line5_Position_cytoflex", 
                    label = "Line5",
                    value = ("2022-05-20")),
          dateInput("Line6_Position_cytoflex", 
                    label = "Line6",
                    value = ("2022-06-20"))),
                 
      tabPanel("Line name", 
          textInput("Line1_Name_cytoflex", 
                    label = "Label line1",
                    value = "Line 1"),
          textInput("Line2_Name_cytoflex", 
                    label = "Label line2",
                    value = "Line 2"),
          textInput("Line3_Name_cytoflex", 
                    label = "Label line3",
                    value = "Line 3"),
          textInput("Line4_Name_cytoflex", 
                    label = "Label line4",
                    value = "Line 4"),
          textInput("Line5_Name_cytoflex", 
                    label = "Label line5",
                    value = "Line 5"),
          textInput("Line6_Name_cytoflex", 
                    label = "Label line6",
                    value = "Line 6")),
                 
       tabPanel("hline options",
          checkboxGroupInput("Hline_cytoflex_1", 
                    label = "Add line",
                    choices = c("Add line")),
          checkboxGroupInput("Hline_cytoflex_2", 
                    label = "Add line",
                    choices = c("Add Hline")),
          textInput("Hline_Position_cytoflex_1", 
                    label = "Position hline",
                    value = "Choose a value for hline"),
          textInput("Hline_Position_cytoflex_2", 
                    label = "Position hline",
                    value = "Choose a value for hline"),
                          
  ))
))