Tab_Plots_CytoflexSRT <- tabItem(tabName = "visualization_data_QC_CytoflexSRT",
  fluidRow(
    tabBox(title = "Generated graph",
          width = 10,
          height = 700,
          tabPanel("Standard Visualization", plotOutput("StandardPlotCytoflexSRT", height = 640)),
          tabPanel("Detailed visualization", plotlyOutput("PlotlyCytoflexSRT", height = 640)),
    ),
    
    box(title = span(icon("chart-line"),"Press to plot"), 
        collapsible = TRUE,  
        width = 2, background = "orange", 
        side = "left",
        actionButton("Generate_Plot_CytoflexSRT",
                      label = "Click here")
    ),
    
    box(title = span(icon("image"),"Download image"), 
        collapsible = TRUE,  
        width = 2, 
        background = "blue",
        uiOutput("Image_CytoflexSRT_plot"),
                                  
    ),
    
    box(title = span(icon("grip-lines-vertical"), "Edit axis ranges"), 
        collapsible = TRUE, 
        solidHeader = TRUE, 
        status = "primary", 
        width = 2,
        uiOutput("Ymin_CytoflexSRT"),
        uiOutput("Ymax_CytoflexSRT"), 
        uiOutput("Xmin_CytoflexSRT"),
        uiOutput("Xmax_CytoflexSRT"), 
    ),
                              
    box(title = span(icon("filter"),"Filters"), 
        collapsible = TRUE, 
        solidHeader = TRUE, 
        width = 3, 
        status = "primary", 
        side = "left",
        uiOutput("Instruments_CytoflexSRT"), 
        uiOutput("Parameters_CytoflexSRT"),
        uiOutput("LasDetec_CytoflexSRT"),
 	uiOutput("PassFail_CytoflexSRT"),  
    ), 
                              
    tabBox(title = "Costumize graph & add Lines and Labels", 
           width = 6,
      tabPanel("Graph title", 
              textInput("Title_Graph_CytoflexSRT", 
                        label = "Title for graph",
                        value = "Graph title")),
      tabPanel("Y-axis title", 
              textInput("Title_Yaxis_CytoflexSRT", 
                        label = "Title for y-axis",
                        value = "y")),
      tabPanel("Add vertical lines", 
              checkboxGroupInput("Add_Lines_CytoflexSRT", 
                                 label = "Add vertical lines",
                                 choices = c("Line1",
                                             "Line2",
                                             "Line3",
                                             "Line4",
                                             "Line5",
                                             "Line6"))),
      tabPanel("Position", 
              dateInput("Line1_Position_CytoflexSRT", 
                        label = "Line1",
                        value = ("2022-01-20")),
              dateInput("Line2_Position_CytoflexSRT", 
                        label = "Line2",
                        value = ("2022-02-20")),
              dateInput("Line3_Position_CytoflexSRT", 
                        label = "Line3",
                        value = ("2022-03-20")),
              dateInput("Line4_Position_CytoflexSRT", 
                        label = "Line4",
                        value = ("2022-04-20")),
              dateInput("Line5_Position_CytoflexSRT", 
                        label = "Line5",
                        value = ("2022-05-20")),
              dateInput("Line6_Position_CytoflexSRT", 
                        label = "Line5",
                        value = ("2022-06-20"))),
      
       tabPanel("Line name", 
              textInput("Line1_Name_CytoflexSRT", 
                         label = "Label line1",
                         value = "Line 1"),
              textInput("Line2_Name_CytoflexSRT", 
                         label = "Label line2",
                         value = "Line 2"),
              textInput("Line3_Name_CytoflexSRT", 
                         label = "Label line3",
                         value = "Line 3"),
              textInput("Line4_Name_CytoflexSRT", 
                         label = "Label line4",
                         value = "Line 4"),
              textInput("Line5_Name_CytoflexSRT", 
                         label = "Label line5",
                         value = "Line 5"),
              textInput("Line6_Name_CytoflexSRT", 
                         label = "Label line6",
                         value = "Line 6")),
                                     
        tabPanel("hline options",
              checkboxGroupInput("Hline_CytoflexSRT_1", 
                                 label = "Add hline_CytoflexSRT",
                                 choices = c("Add line")),
              checkboxGroupInput("Hline_CytoflexSRT_2", 
                                 label = "Add hline_CytoflexSRT",
                                 choices = c("Add line")),
              textInput("Hline_Position_CytoflexSRT_1", 
                                 label = "Position hline",
                                 value = "Choose a value for hline"),
              textInput("Hline_Position_CytoflexSRT_2", 
                                 label = "Position hline",
                                 value = "Choose a value for hline"))
    ) 
                              
 )
)